name: motohub
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  file_picker: '>=8.1.2'
  latlong2: 0.9.1
  flutter_map: ^8.0.0
  http: ^1.0.0
  fl_chart: 0.68.0
  flutter_local_notifications: ^19.5.0
  url_launcher: ^6.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^16.2.0
  provider: ^6.1.2
  supabase_flutter: '>=1.10.0'
  geolocator: 13.0.4
  permission_handler: ^12.0.0
  image_picker: '>=1.1.2'
  intl: 0.20.2
  cached_network_image: ^3.0.0
  shimmer: ^3.0.0
  flutter_secure_storage: ^10.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  workmanager: ^0.5.2
  battery_plus: ^6.0.2
  path_provider: ^2.1.5
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
